- name: Hello World Sample
  hosts: localhost
  tasks:
  - name: Pause for 3 minutes to build app cache
    shell: sleep 3m
    register: csarDdeploySvs
    async: 5000
    poll: 0
  - name: Check sync status
    become: yes
    async_status:
      jid: "{{ csarDdeploySvs.ansible_job_id }}"
    register: async_poll_results
    until: async_poll_results.finished
    retries: 300
    poll: 60
    delay: 30
    delegate_to: localhost
    vars:
      ansible_async_dir: /home/runner/.ansible_async









